# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVCHD1zbrrF9LT99tqgkXMaUvBSWx0l4
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("FEMA Disaster Relief Dashboard")
st.markdown("**Completed By:** Gabi Turgeon & Vicky Gutierrez")

#Load shortened sample FEMA dataset
#option 1 same repo as app
df = pd.read_csv("fema_sample.csv")

st.subheader("Data Preview")
st.write(df.head())

#histogram of repair amount
st.subheader("Histogram of Repair Amount")
fig_hist = px.histogram(df, x="repairAmount", nbins = 30, title = "Distribution of Repair Amounts")
st.plotly_chart(fig_hist)

#boxplot of Repair Amount by TSA Eligibility
st.subheader("Boxplot of Repair Amount by TSA Eligibility")
fig_box = px.box(df, x="tsaEligible", y="repairAmount", title="Repair Amount by TSA Eligibility",
labels = {"tsaEligible": "TSA Eligible (1=Yes, 0=No)", "repairAmount": "Repair Amount"})
st.plotly_chart(fig_box)

#Test Summary
st.markdown("*Insight:* Compare the central tendency and spread of repair amounts for TSA-eligible va non-eligible households.*")